# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Administrator/.nuke/Batch_Render\UI\MainUI.ui'
#
# Created: Sun Jun 16 23:43:23 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Nuke_BatchRender(object):
    def setupUi(self, Nuke_BatchRender):
        Nuke_BatchRender.setObjectName("Nuke_BatchRender")
        Nuke_BatchRender.resize(802, 719)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main_Window/Window_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Nuke_BatchRender.setWindowIcon(icon)
        Nuke_BatchRender.setStyleSheet("font: 9pt \"Cambria\";")
        self.tabWidget = QtWidgets.QTabWidget(Nuke_BatchRender)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(340, 20, 441, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.Write = QtWidgets.QWidget()
        self.Write.setObjectName("Write")
        self.layoutWidget = QtWidgets.QWidget(self.Write)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 24, 385, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.channel_label = QtWidgets.QLabel(self.layoutWidget)
        self.channel_label.setMaximumSize(QtCore.QSize(50, 50))
        self.channel_label.setStyleSheet("font: 9pt \"Cambria\";")
        self.channel_label.setObjectName("channel_label")
        self.horizontalLayout.addWidget(self.channel_label)
        self.channels = QtWidgets.QComboBox(self.layoutWidget)
        self.channels.setStyleSheet("font: 9pt \"Cambria\";")
        self.channels.setObjectName("channels")
        self.channels.addItem("")
        self.channels.addItem("")
        self.channels.addItem("")
        self.channels.addItem("")
        self.channels.addItem("")
        self.channels.addItem("")
        self.horizontalLayout.addWidget(self.channels)
        self.red = QtWidgets.QCheckBox(self.layoutWidget)
        self.red.setMaximumSize(QtCore.QSize(40, 40))
        self.red.setAcceptDrops(False)
        self.red.setStyleSheet("font: 9pt \"Cambria\";")
        self.red.setChecked(True)
        self.red.setObjectName("red")
        self.horizontalLayout.addWidget(self.red)
        self.green = QtWidgets.QCheckBox(self.layoutWidget)
        self.green.setMaximumSize(QtCore.QSize(50, 50))
        self.green.setStyleSheet("font: 9pt \"Cambria\";")
        self.green.setChecked(True)
        self.green.setObjectName("green")
        self.horizontalLayout.addWidget(self.green)
        self.blue = QtWidgets.QCheckBox(self.layoutWidget)
        self.blue.setMaximumSize(QtCore.QSize(45, 45))
        self.blue.setChecked(True)
        self.blue.setObjectName("blue")
        self.horizontalLayout.addWidget(self.blue)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setMaximumSize(QtCore.QSize(15, 15))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.channels_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.channels_2.setMinimumSize(QtCore.QSize(90, 0))
        self.channels_2.setObjectName("channels_2")
        self.channels_2.addItem("")
        self.channels_2.addItem("")
        self.channels_2.addItem("")
        self.channels_2.addItem("")
        self.channels_2.addItem("")
        self.horizontalLayout.addWidget(self.channels_2)
        self.reading = QtWidgets.QCheckBox(self.Write)
        self.reading.setGeometry(QtCore.QRect(110, 330, 77, 20))
        self.reading.setMinimumSize(QtCore.QSize(0, 20))
        self.reading.setMaximumSize(QtCore.QSize(80, 20))
        self.reading.setObjectName("reading")
        self.layoutWidget1 = QtWidgets.QWidget(self.Write)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 136, 381, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.colorspace_label = QtWidgets.QLabel(self.layoutWidget1)
        self.colorspace_label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.colorspace_label.setStyleSheet("font: 9pt \"Cambria\";")
        self.colorspace_label.setObjectName("colorspace_label")
        self.horizontalLayout_5.addWidget(self.colorspace_label)
        self.colorspace = QtWidgets.QComboBox(self.layoutWidget1)
        self.colorspace.setStyleSheet("font: 9pt \"Cambria\";")
        self.colorspace.setObjectName("colorspace")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.colorspace.addItem("")
        self.horizontalLayout_5.addWidget(self.colorspace)
        self.premultiplied = QtWidgets.QCheckBox(self.layoutWidget1)
        self.premultiplied.setStyleSheet("font: 9pt \"Cambria\";")
        self.premultiplied.setObjectName("premultiplied")
        self.horizontalLayout_5.addWidget(self.premultiplied)
        self.raw = QtWidgets.QCheckBox(self.layoutWidget1)
        self.raw.setStyleSheet("font: 9pt \"Cambria\";")
        self.raw.setObjectName("raw")
        self.horizontalLayout_5.addWidget(self.raw)
        self.layoutWidget2 = QtWidgets.QWidget(self.Write)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 108, 381, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label = QtWidgets.QLabel(self.layoutWidget2)
        self.frame_label.setStyleSheet("font: 9pt \"Cambria\";")
        self.frame_label.setObjectName("frame_label")
        self.horizontalLayout_4.addWidget(self.frame_label)
        self.frame_mode = QtWidgets.QComboBox(self.layoutWidget2)
        self.frame_mode.setStyleSheet("font: 9pt \"Cambria\";")
        self.frame_mode.setObjectName("frame_mode")
        self.frame_mode.addItem("")
        self.frame_mode.addItem("")
        self.frame_mode.addItem("")
        self.horizontalLayout_4.addWidget(self.frame_mode)
        self.frame = QtWidgets.QLineEdit(self.layoutWidget2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4.addWidget(self.frame)
        self.layoutWidget3 = QtWidgets.QWidget(self.Write)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 270, 243, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setMinimumSize(QtCore.QSize(75, 0))
        self.label_8.setMaximumSize(QtCore.QSize(75, 30))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.render_order = QtWidgets.QLineEdit(self.layoutWidget3)
        self.render_order.setMaximumSize(QtCore.QSize(80, 20))
        self.render_order.setObjectName("render_order")
        self.horizontalLayout_8.addWidget(self.render_order)
        self.Render_pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.Render_pushButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Render_pushButton.setObjectName("Render_pushButton")
        self.horizontalLayout_8.addWidget(self.Render_pushButton)
        self.layoutWidget4 = QtWidgets.QWidget(self.Write)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 350, 398, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_10.setEnabled(False)
        self.label_10.setMinimumSize(QtCore.QSize(90, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.on_error = QtWidgets.QComboBox(self.layoutWidget4)
        self.on_error.setEnabled(False)
        self.on_error.setObjectName("on_error")
        self.on_error.addItem("")
        self.on_error.addItem("")
        self.on_error.addItem("")
        self.on_error.addItem("")
        self.horizontalLayout_10.addWidget(self.on_error)
        self.Reload_pushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.Reload_pushButton.setEnabled(False)
        self.Reload_pushButton.setObjectName("Reload_pushButton")
        self.horizontalLayout_10.addWidget(self.Reload_pushButton)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_10.setMinimumSize(QtCore.QSize(110, 0))
        self.checkBox_10.setMaximumSize(QtCore.QSize(110, 16777215))
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_10.addWidget(self.checkBox_10)
        self.line_2 = QtWidgets.QFrame(self.Write)
        self.line_2.setGeometry(QtCore.QRect(-1, 230, 451, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.create_directories = QtWidgets.QCheckBox(self.Write)
        self.create_directories.setGeometry(QtCore.QRect(110, 250, 130, 16))
        self.create_directories.setMaximumSize(QtCore.QSize(130, 16777215))
        self.create_directories.setObjectName("create_directories")
        self.layoutWidget5 = QtWidgets.QWidget(self.Write)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 300, 351, 27))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_9.setEnabled(False)
        self.label_9.setMinimumSize(QtCore.QSize(75, 25))
        self.label_9.setMaximumSize(QtCore.QSize(75, 25))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.first = QtWidgets.QLineEdit(self.layoutWidget5)
        self.first.setEnabled(False)
        self.first.setMaximumSize(QtCore.QSize(80, 20))
        self.first.setObjectName("first")
        self.horizontalLayout_9.addWidget(self.first)
        self.last = QtWidgets.QLineEdit(self.layoutWidget5)
        self.last.setEnabled(False)
        self.last.setMaximumSize(QtCore.QSize(80, 20))
        self.last.setObjectName("last")
        self.horizontalLayout_9.addWidget(self.last)
        self.use_limit = QtWidgets.QCheckBox(self.layoutWidget5)
        self.use_limit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.use_limit.setObjectName("use_limit")
        self.horizontalLayout_9.addWidget(self.use_limit)
        self.layoutWidget6 = QtWidgets.QWidget(self.Write)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 164, 381, 22))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.views_label = QtWidgets.QLabel(self.layoutWidget6)
        self.views_label.setStyleSheet("font: 9pt \"Cambria\";")
        self.views_label.setObjectName("views_label")
        self.horizontalLayout_6.addWidget(self.views_label)
        self.views = QtWidgets.QComboBox(self.layoutWidget6)
        self.views.setMinimumSize(QtCore.QSize(308, 0))
        self.views.setMaximumSize(QtCore.QSize(80, 16777215))
        self.views.setMouseTracking(False)
        self.views.setAcceptDrops(False)
        self.views.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.views.setAutoFillBackground(False)
        self.views.setStyleSheet("font: 9pt \"Cambria\";")
        self.views.setObjectName("views")
        self.views.addItem("")
        self.horizontalLayout_6.addWidget(self.views)
        self.layoutWidget7 = QtWidgets.QWidget(self.Write)
        self.layoutWidget7.setGeometry(QtCore.QRect(30, 192, 123, 22))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filetype_label = QtWidgets.QLabel(self.layoutWidget7)
        self.filetype_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.filetype_label.setStyleSheet("font: 9pt \"Cambria\";")
        self.filetype_label.setObjectName("filetype_label")
        self.horizontalLayout_7.addWidget(self.filetype_label)
        self.file_type = QtWidgets.QComboBox(self.layoutWidget7)
        self.file_type.setEditable(False)
        self.file_type.setMaxVisibleItems(30)
        self.file_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.file_type.setObjectName("file_type")
        self.file_type.addItem("")
        self.file_type.setItemText(0, "")
        self.file_type.addItem("")
        self.file_type.addItem("")
        self.file_type.addItem("")
        self.file_type.addItem("")
        self.horizontalLayout_7.addWidget(self.file_type)
        self.layoutWidget8 = QtWidgets.QWidget(self.Write)
        self.layoutWidget8.setGeometry(QtCore.QRect(31, 50, 381, 25))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_label = QtWidgets.QLabel(self.layoutWidget8)
        self.file_label.setMinimumSize(QtCore.QSize(30, 0))
        self.file_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.file_label.setStyleSheet("font: 9pt \"Cambria\";")
        self.file_label.setObjectName("file_label")
        self.horizontalLayout_2.addWidget(self.file_label)
        self.file = QtWidgets.QLineEdit(self.layoutWidget8)
        self.file.setMaximumSize(QtCore.QSize(450, 20))
        self.file.setObjectName("file")
        self.horizontalLayout_2.addWidget(self.file)
        self.file_pushButton = QtWidgets.QPushButton(self.layoutWidget8)
        self.file_pushButton.setMinimumSize(QtCore.QSize(20, 0))
        self.file_pushButton.setMaximumSize(QtCore.QSize(30, 20))
        self.file_pushButton.setStyleSheet("border: 1px solid gray;\n"
"border-radius:4px;")
        self.file_pushButton.setObjectName("file_pushButton")
        self.horizontalLayout_2.addWidget(self.file_pushButton)
        self.layoutWidget9 = QtWidgets.QWidget(self.Write)
        self.layoutWidget9.setGeometry(QtCore.QRect(31, 80, 381, 25))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.proxy_lable = QtWidgets.QLabel(self.layoutWidget9)
        self.proxy_lable.setMaximumSize(QtCore.QSize(16777215, 20))
        self.proxy_lable.setStyleSheet("font: 9pt \"Cambria\";")
        self.proxy_lable.setObjectName("proxy_lable")
        self.horizontalLayout_3.addWidget(self.proxy_lable)
        self.proxy = QtWidgets.QLineEdit(self.layoutWidget9)
        self.proxy.setMaximumSize(QtCore.QSize(450, 20))
        self.proxy.setObjectName("proxy")
        self.horizontalLayout_3.addWidget(self.proxy)
        self.Prxoy_pushButton = QtWidgets.QPushButton(self.layoutWidget9)
        self.Prxoy_pushButton.setMinimumSize(QtCore.QSize(20, 0))
        self.Prxoy_pushButton.setMaximumSize(QtCore.QSize(80, 20))
        self.Prxoy_pushButton.setStyleSheet("border: 1px solid gray;\n"
"border-radius:4px;")
        self.Prxoy_pushButton.setAutoRepeat(False)
        self.Prxoy_pushButton.setAutoExclusive(False)
        self.Prxoy_pushButton.setAutoDefault(False)
        self.Prxoy_pushButton.setDefault(False)
        self.Prxoy_pushButton.setFlat(False)
        self.Prxoy_pushButton.setObjectName("Prxoy_pushButton")
        self.horizontalLayout_3.addWidget(self.Prxoy_pushButton)
        self.tabWidget.addTab(self.Write, "")
        self.OCIO = QtWidgets.QWidget()
        self.OCIO.setObjectName("OCIO")
        self.layoutWidget10 = QtWidgets.QWidget(self.OCIO)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 20, 411, 21))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_11.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget10)
        self.line_3.setMinimumSize(QtCore.QSize(150, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_11.addWidget(self.line_3)
        self.layoutWidget11 = QtWidgets.QWidget(self.OCIO)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 50, 391, 111))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.key1 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.key1.setObjectName("key1")
        self.horizontalLayout_12.addWidget(self.key1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_13.setMaximumSize(QtCore.QSize(50, 30))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.value1 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.value1.setObjectName("value1")
        self.horizontalLayout_12.addWidget(self.value1)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.key2 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.key2.setObjectName("key2")
        self.horizontalLayout_14.addWidget(self.key2)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_17.setMaximumSize(QtCore.QSize(50, 30))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.value2 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.value2.setObjectName("value2")
        self.horizontalLayout_14.addWidget(self.value2)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.key3 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.key3.setObjectName("key3")
        self.horizontalLayout_15.addWidget(self.key3)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_19.setMaximumSize(QtCore.QSize(50, 30))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.value3 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.value3.setObjectName("value3")
        self.horizontalLayout_15.addWidget(self.value3)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.key4 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.key4.setObjectName("key4")
        self.horizontalLayout_16.addWidget(self.key4)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_21.setMaximumSize(QtCore.QSize(50, 30))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.value4 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.value4.setObjectName("value4")
        self.horizontalLayout_16.addWidget(self.value4)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.OCIO, "")
        self.Python = QtWidgets.QWidget()
        self.Python.setObjectName("Python")
        self.layoutWidget12 = QtWidgets.QWidget(self.Python)
        self.layoutWidget12.setGeometry(QtCore.QRect(0, 10, 441, 151))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.beforeRender = QtWidgets.QLineEdit(self.layoutWidget12)
        self.beforeRender.setObjectName("beforeRender")
        self.horizontalLayout_17.addWidget(self.beforeRender)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.beforeFrameRender = QtWidgets.QLineEdit(self.layoutWidget12)
        self.beforeFrameRender.setObjectName("beforeFrameRender")
        self.horizontalLayout_18.addWidget(self.beforeFrameRender)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.afterFrameRender = QtWidgets.QLineEdit(self.layoutWidget12)
        self.afterFrameRender.setObjectName("afterFrameRender")
        self.horizontalLayout_19.addWidget(self.afterFrameRender)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.afterRender = QtWidgets.QLineEdit(self.layoutWidget12)
        self.afterRender.setObjectName("afterRender")
        self.horizontalLayout_20.addWidget(self.afterRender)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        self.renderProgress = QtWidgets.QLineEdit(self.layoutWidget12)
        self.renderProgress.setObjectName("renderProgress")
        self.horizontalLayout_21.addWidget(self.renderProgress)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.tabWidget.addTab(self.Python, "")
        self.Node = QtWidgets.QWidget()
        self.Node.setObjectName("Node")
        self.label = QtWidgets.QPlainTextEdit(self.Node)
        self.label.setGeometry(QtCore.QRect(60, 20, 361, 211))
        self.label.setObjectName("label")
        self.label_27 = QtWidgets.QLabel(self.Node)
        self.label_27.setGeometry(QtCore.QRect(20, 20, 31, 16))
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.Node, "")
        self.label_28 = QtWidgets.QLabel(Nuke_BatchRender)
        self.label_28.setGeometry(QtCore.QRect(10, 15, 54, 12))
        self.label_28.setObjectName("label_28")
        self.line_4 = QtWidgets.QFrame(Nuke_BatchRender)
        self.line_4.setGeometry(QtCore.QRect(70, 15, 251, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Run_button = QtWidgets.QPushButton(Nuke_BatchRender)
        self.Run_button.setGeometry(QtCore.QRect(340, 655, 50, 50))
        self.Run_button.setStyleSheet("QPushButton{\n"
"border-image: url(:/Main_Window/render all.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/render_hover.png);\n"
"}\n"
"QPushButton:checked{\n"
"    border-image: url(:/Main_Window/suspend.png);\n"
"}\n"
"QPushButton:checked:hover{\n"
"    border-image: url(:/Main_Window/suspend_hover.png);\n"
"}")
        self.Run_button.setText("")
        self.Run_button.setCheckable(True)
        self.Run_button.setFlat(False)
        self.Run_button.setObjectName("Run_button")
        self.line = QtWidgets.QFrame(Nuke_BatchRender)
        self.line.setGeometry(QtCore.QRect(340, 635, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_6 = QtWidgets.QFrame(Nuke_BatchRender)
        self.line_6.setGeometry(QtCore.QRect(320, 10, 20, 751))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Write_pushButton = QtWidgets.QPushButton(Nuke_BatchRender)
        self.Write_pushButton.setGeometry(QtCore.QRect(340, 595, 121, 31))
        self.Write_pushButton.setStyleSheet("QPushButton{\n"
"border: 1px solid gray;\n"
"border-radius:10px;\n"
"font: 9pt \"Cambria\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(221, 232, 235);\n"
"border: 1px solid gray;\n"
"border-radius:10px;\n"
"font: 9pt \"Cambria\";\n"
"}\n"
"")
        self.Write_pushButton.setObjectName("Write_pushButton")
        self.Add_Button = QtWidgets.QPushButton(Nuke_BatchRender)
        self.Add_Button.setGeometry(QtCore.QRect(10, 660, 40, 40))
        self.Add_Button.setStyleSheet("QPushButton{\n"
"border-image: url(:/Main_Window/add.png);\n"
"border: 1px solid gray;\n"
"border-radius:20px;}\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/add_hover.png);\n"
"border: 1px solid gray;\n"
"border-radius:20px;}")
        self.Add_Button.setText("")
        self.Add_Button.setObjectName("Add_Button")
        self.line_5 = QtWidgets.QFrame(Nuke_BatchRender)
        self.line_5.setGeometry(QtCore.QRect(340, 440, 451, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.Nukefile_list = QtWidgets.QListWidget(Nuke_BatchRender)
        self.Nukefile_list.setGeometry(QtCore.QRect(10, 40, 311, 601))
        self.Nukefile_list.setDragEnabled(False)
        self.Nukefile_list.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.Nukefile_list.setObjectName("Nukefile_list")
        self.Nuke_vresion = QtWidgets.QComboBox(Nuke_BatchRender)
        self.Nuke_vresion.setGeometry(QtCore.QRect(240, 670, 71, 21))
        self.Nuke_vresion.setObjectName("Nuke_vresion")
        self.Nuke_vresion.addItem("")
        self.Nuke_vresion.addItem("")
        self.Nuke_vresion.addItem("")
        self.vresion_lable = QtWidgets.QLabel(Nuke_BatchRender)
        self.vresion_lable.setGeometry(QtCore.QRect(160, 670, 71, 21))
        self.vresion_lable.setStyleSheet("font: 9pt \"Cambria\";")
        self.vresion_lable.setObjectName("vresion_lable")
        self.groupBox = QtWidgets.QGroupBox(Nuke_BatchRender)
        self.groupBox.setGeometry(QtCore.QRect(340, 535, 451, 51))
        self.groupBox.setStyleSheet("font: 9pt \"Cambria\";")
        self.groupBox.setObjectName("groupBox")
        self.SqeNuke_lable = QtWidgets.QLabel(self.groupBox)
        self.SqeNuke_lable.setGeometry(QtCore.QRect(11, 20, 101, 21))
        self.SqeNuke_lable.setStyleSheet("font: 9pt \"Cambria\";")
        self.SqeNuke_lable.setObjectName("SqeNuke_lable")
        self.OutfilePath = QtWidgets.QLineEdit(self.groupBox)
        self.OutfilePath.setGeometry(QtCore.QRect(115, 20, 291, 21))
        self.OutfilePath.setObjectName("OutfilePath")
        self.SqeNuke_Button = QtWidgets.QPushButton(self.groupBox)
        self.SqeNuke_Button.setGeometry(QtCore.QRect(410, 14, 30, 30))
        self.SqeNuke_Button.setMaximumSize(QtCore.QSize(50, 60))
        self.SqeNuke_Button.setStyleSheet("QPushButton{\n"
"border-image: url(:/Main_Window/open.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/open_hover.png);\n"
"}")
        self.SqeNuke_Button.setText("")
        self.SqeNuke_Button.setObjectName("SqeNuke_Button")
        self.groupBox_2 = QtWidgets.QGroupBox(Nuke_BatchRender)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 465, 451, 51))
        self.groupBox_2.setStyleSheet("font: 9pt \"Cambria\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.Sequence_file_lable = QtWidgets.QLabel(self.groupBox_2)
        self.Sequence_file_lable.setGeometry(QtCore.QRect(30, 20, 81, 21))
        self.Sequence_file_lable.setStyleSheet("font: 9pt \"Cambria\";")
        self.Sequence_file_lable.setObjectName("Sequence_file_lable")
        self.Sequence_Path = QtWidgets.QLineEdit(self.groupBox_2)
        self.Sequence_Path.setGeometry(QtCore.QRect(115, 20, 291, 21))
        self.Sequence_Path.setObjectName("Sequence_Path")
        self.Sequence_file_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Sequence_file_button.setGeometry(QtCore.QRect(410, 14, 30, 30))
        self.Sequence_file_button.setMaximumSize(QtCore.QSize(50, 60))
        self.Sequence_file_button.setStyleSheet("QPushButton{\n"
"border-image: url(:/Main_Window/open.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/open_hover.png);\n"
"}")
        self.Sequence_file_button.setText("")
        self.Sequence_file_button.setObjectName("Sequence_file_button")
        self.Clean_Button = QtWidgets.QPushButton(Nuke_BatchRender)
        self.Clean_Button.setGeometry(QtCore.QRect(110, 660, 40, 40))
        self.Clean_Button.setStyleSheet("QPushButton{\n"
"border: 1px solid gray;\n"
"border-image: url(:/Main_Window/clear.png);\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/clear_hover.png);\n"
"}")
        self.Clean_Button.setText("")
        self.Clean_Button.setObjectName("Clean_Button")
        self.progressBar = QtWidgets.QProgressBar(Nuke_BatchRender)
        self.progressBar.setGeometry(QtCore.QRect(500, 600, 291, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Cancel_button_ = QtWidgets.QPushButton(Nuke_BatchRender)
        self.Cancel_button_.setGeometry(QtCore.QRect(400, 655, 50, 50))
        self.Cancel_button_.setStyleSheet("QPushButton{\n"
"border-image: url(:/Main_Window/kill.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/kill_hover.png);\n"
"}")
        self.Cancel_button_.setText("")
        self.Cancel_button_.setFlat(False)
        self.Cancel_button_.setObjectName("Cancel_button_")
        self.Run_progressBar = QtWidgets.QProgressBar(Nuke_BatchRender)
        self.Run_progressBar.setGeometry(QtCore.QRect(630, 650, 161, 21))
        self.Run_progressBar.setProperty("value", 0)
        self.Run_progressBar.setObjectName("Run_progressBar")
        self.Remove_Button = QtWidgets.QPushButton(Nuke_BatchRender)
        self.Remove_Button.setGeometry(QtCore.QRect(60, 660, 40, 40))
        self.Remove_Button.setStyleSheet("QPushButton{\n"
"border-image: url(:/Main_Window/remove.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/Main_Window/remove_hover.png);\n"
"}")
        self.Remove_Button.setText("")
        self.Remove_Button.setObjectName("Remove_Button")
        self.Massage_progressBar = QtWidgets.QProgressBar(Nuke_BatchRender)
        self.Massage_progressBar.setGeometry(QtCore.QRect(480, 680, 301, 16))
        self.Massage_progressBar.setStyleSheet("border: 1px solid gray;\n"
"border-radius:3px;")
        self.Massage_progressBar.setProperty("value", 0)
        self.Massage_progressBar.setTextVisible(False)
        self.Massage_progressBar.setObjectName("Massage_progressBar")

        self.retranslateUi(Nuke_BatchRender)
        self.tabWidget.setCurrentIndex(0)
        self.reading.toggled['bool'].connect(self.label_10.setEnabled)
        self.reading.toggled['bool'].connect(self.on_error.setEnabled)
        self.reading.toggled['bool'].connect(self.Reload_pushButton.setEnabled)
        self.reading.toggled['bool'].connect(self.Render_pushButton.setDisabled)
        self.use_limit.toggled['bool'].connect(self.last.setEnabled)
        self.use_limit.toggled['bool'].connect(self.first.setEnabled)
        self.use_limit.toggled['bool'].connect(self.label_9.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Nuke_BatchRender)

    def retranslateUi(self, Nuke_BatchRender):
        _translate = QtCore.QCoreApplication.translate
        Nuke_BatchRender.setWindowTitle(_translate("Nuke_BatchRender", "Nuke_BatchRender"))
        self.channel_label.setText(_translate("Nuke_BatchRender", "channels"))
        self.channels.setItemText(0, _translate("Nuke_BatchRender", "all"))
        self.channels.setItemText(1, _translate("Nuke_BatchRender", "none"))
        self.channels.setItemText(2, _translate("Nuke_BatchRender", "rgb"))
        self.channels.setItemText(3, _translate("Nuke_BatchRender", "rgba"))
        self.channels.setItemText(4, _translate("Nuke_BatchRender", "alpha"))
        self.channels.setItemText(5, _translate("Nuke_BatchRender", "new"))
        self.red.setText(_translate("Nuke_BatchRender", "red"))
        self.green.setText(_translate("Nuke_BatchRender", "green"))
        self.blue.setText(_translate("Nuke_BatchRender", "blue"))
        self.channels_2.setItemText(0, _translate("Nuke_BatchRender", "none"))
        self.channels_2.setItemText(1, _translate("Nuke_BatchRender", "rgba.red"))
        self.channels_2.setItemText(2, _translate("Nuke_BatchRender", "rgba.green"))
        self.channels_2.setItemText(3, _translate("Nuke_BatchRender", "rgba.blue"))
        self.channels_2.setItemText(4, _translate("Nuke_BatchRender", "rgba.alpha"))
        self.reading.setText(_translate("Nuke_BatchRender", "read file"))
        self.colorspace_label.setText(_translate("Nuke_BatchRender", "colorspace"))
        self.colorspace.setItemText(0, _translate("Nuke_BatchRender", "default"))
        self.colorspace.setItemText(1, _translate("Nuke_BatchRender", "liner"))
        self.colorspace.setItemText(2, _translate("Nuke_BatchRender", "sRGB"))
        self.colorspace.setItemText(3, _translate("Nuke_BatchRender", "rec709"))
        self.colorspace.setItemText(4, _translate("Nuke_BatchRender", "Cineon"))
        self.colorspace.setItemText(5, _translate("Nuke_BatchRender", "Gamma1.8"))
        self.colorspace.setItemText(6, _translate("Nuke_BatchRender", "Gamma2.2"))
        self.colorspace.setItemText(7, _translate("Nuke_BatchRender", "Gamma2.4"))
        self.colorspace.setItemText(8, _translate("Nuke_BatchRender", "Gamma2.6"))
        self.colorspace.setItemText(9, _translate("Nuke_BatchRender", "panalog"))
        self.colorspace.setItemText(10, _translate("Nuke_BatchRender", "REDLog"))
        self.colorspace.setItemText(11, _translate("Nuke_BatchRender", "ViperLog"))
        self.colorspace.setItemText(12, _translate("Nuke_BatchRender", "AlexaV3LogC"))
        self.colorspace.setItemText(13, _translate("Nuke_BatchRender", "PLogLin"))
        self.colorspace.setItemText(14, _translate("Nuke_BatchRender", "SLog"))
        self.colorspace.setItemText(15, _translate("Nuke_BatchRender", "SLog1"))
        self.colorspace.setItemText(16, _translate("Nuke_BatchRender", "SLog2"))
        self.colorspace.setItemText(17, _translate("Nuke_BatchRender", "SLog3"))
        self.colorspace.setItemText(18, _translate("Nuke_BatchRender", "CLog"))
        self.colorspace.setItemText(19, _translate("Nuke_BatchRender", "Log3G10"))
        self.colorspace.setItemText(20, _translate("Nuke_BatchRender", "Log3G12"))
        self.colorspace.setItemText(21, _translate("Nuke_BatchRender", "HybridLogGamma"))
        self.colorspace.setItemText(22, _translate("Nuke_BatchRender", "Protune"))
        self.colorspace.setItemText(23, _translate("Nuke_BatchRender", "BT1886"))
        self.colorspace.setItemText(24, _translate("Nuke_BatchRender", "HDR2084"))
        self.premultiplied.setText(_translate("Nuke_BatchRender", "premultiplied"))
        self.raw.setText(_translate("Nuke_BatchRender", "raw data"))
        self.frame_label.setText(_translate("Nuke_BatchRender", "frame"))
        self.frame_mode.setItemText(0, _translate("Nuke_BatchRender", "expression"))
        self.frame_mode.setItemText(1, _translate("Nuke_BatchRender", "start at"))
        self.frame_mode.setItemText(2, _translate("Nuke_BatchRender", "offest"))
        self.label_8.setText(_translate("Nuke_BatchRender", "render order"))
        self.render_order.setText(_translate("Nuke_BatchRender", "1"))
        self.Render_pushButton.setText(_translate("Nuke_BatchRender", "Render"))
        self.label_10.setText(_translate("Nuke_BatchRender", "missing frames"))
        self.on_error.setItemText(0, _translate("Nuke_BatchRender", "error"))
        self.on_error.setItemText(1, _translate("Nuke_BatchRender", "black"))
        self.on_error.setItemText(2, _translate("Nuke_BatchRender", "checkerboard"))
        self.on_error.setItemText(3, _translate("Nuke_BatchRender", "read input"))
        self.Reload_pushButton.setText(_translate("Nuke_BatchRender", "Reload"))
        self.checkBox_10.setText(_translate("Nuke_BatchRender", "read all lines"))
        self.create_directories.setText(_translate("Nuke_BatchRender", "create directories"))
        self.label_9.setText(_translate("Nuke_BatchRender", "frame order"))
        self.first.setText(_translate("Nuke_BatchRender", "1"))
        self.last.setText(_translate("Nuke_BatchRender", "1"))
        self.use_limit.setText(_translate("Nuke_BatchRender", "limit to range"))
        self.views_label.setText(_translate("Nuke_BatchRender", "     views"))
        self.views.setItemText(0, _translate("Nuke_BatchRender", "main"))
        self.filetype_label.setText(_translate("Nuke_BatchRender", "   file type"))
        self.file_type.setItemText(1, _translate("Nuke_BatchRender", "exr"))
        self.file_type.setItemText(2, _translate("Nuke_BatchRender", "jpeg"))
        self.file_type.setItemText(3, _translate("Nuke_BatchRender", "mov"))
        self.file_type.setItemText(4, _translate("Nuke_BatchRender", "png"))
        self.file_label.setText(_translate("Nuke_BatchRender", "file"))
        self.file_pushButton.setText(_translate("Nuke_BatchRender", "..."))
        self.proxy_lable.setText(_translate("Nuke_BatchRender", "Proxy"))
        self.Prxoy_pushButton.setText(_translate("Nuke_BatchRender", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Write), _translate("Nuke_BatchRender", "Write"))
        self.label_11.setText(_translate("Nuke_BatchRender", "Context"))
        self.label_12.setText(_translate("Nuke_BatchRender", "key1"))
        self.label_13.setText(_translate("Nuke_BatchRender", "value1"))
        self.label_16.setText(_translate("Nuke_BatchRender", "key2"))
        self.label_17.setText(_translate("Nuke_BatchRender", "value2"))
        self.label_18.setText(_translate("Nuke_BatchRender", "key3"))
        self.label_19.setText(_translate("Nuke_BatchRender", "value3"))
        self.label_20.setText(_translate("Nuke_BatchRender", "key4"))
        self.label_21.setText(_translate("Nuke_BatchRender", "value4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OCIO), _translate("Nuke_BatchRender", "OCIO"))
        self.label_22.setText(_translate("Nuke_BatchRender", "      before render"))
        self.label_23.setText(_translate("Nuke_BatchRender", " before each render"))
        self.label_24.setText(_translate("Nuke_BatchRender", "   after each frame"))
        self.label_25.setText(_translate("Nuke_BatchRender", "       after render"))
        self.label_26.setText(_translate("Nuke_BatchRender", "    redner progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Python), _translate("Nuke_BatchRender", "Python"))
        self.label_27.setText(_translate("Nuke_BatchRender", "label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Node), _translate("Nuke_BatchRender", "Node"))
        self.label_28.setText(_translate("Nuke_BatchRender", "Nuke_file"))
        self.Run_button.setToolTip(_translate("Nuke_BatchRender", "<html><head/><body><p><br/></p></body></html>"))
        self.Write_pushButton.setText(_translate("Nuke_BatchRender", "Creat Write Node"))
        self.Nuke_vresion.setItemText(0, _translate("Nuke_BatchRender", "Nuke11"))
        self.Nuke_vresion.setItemText(1, _translate("Nuke_BatchRender", "Nuke10"))
        self.Nuke_vresion.setItemText(2, _translate("Nuke_BatchRender", "Nuke9"))
        self.vresion_lable.setText(_translate("Nuke_BatchRender", "Nuke version "))
        self.groupBox.setTitle(_translate("Nuke_BatchRender", "NukeSqe_file"))
        self.SqeNuke_lable.setText(_translate("Nuke_BatchRender", "Nukefile Save as"))
        self.groupBox_2.setTitle(_translate("Nuke_BatchRender", "Sequence"))
        self.Sequence_file_lable.setText(_translate("Nuke_BatchRender", "Sequence_Path"))
        self.Cancel_button_.setToolTip(_translate("Nuke_BatchRender", "<html><head/><body><p><br/></p></body></html>"))

import Icon_rc
